### ISSUE TITLE
Running in local and please update README.md

### ISSUE THREAD

**Issue by kresnasatya** [cristianbote/hnpwa-vanilla#10]
Hi Cristian, thanks for your awesome hnpwa-vanilla repo. I just want to learn the code and how it works, but when I do ```npm run dev``` as per documentation it doesn't work. I check in **package.json** and it doesn't contain ```"scripts": { "dev": "bla bla bla" }```. I go to your commit history and it shows that you replace several dependecies with **microbundle** and you remove the ```scripts { "dev": "bla bla bla" }```. I go to microbundle repository and do as per documentation:

1. ```npm i -D microbundle```
2. In **package.json** I add dev env in scripts: ```"scripts": { "build": "microbundle",
    "dev": "microbundle watch" }```
3. ```npm run dev``` but it just bundling and didn't show the URL that I must hit in browser.

Could you please give the solution about this with update README.md. Thanks a lot.

**Comment by cristianbote** [comment]
Hey Satya!

First of all, thank you for submitting the issue! Really appreciate it.

Second, indeed, when switching to `microbundle` I skipped the `dev` script. Usually I just run a `python -m SimpleHTTPServer 8080` in my `dist` folder 😄, not really dev oriented.
I'll add it back asap.

Thanks again!
