### ISSUE TITLE
Missing script for npm run serve and run-prod

### ISSUE THREAD

**Issue by steventsao** [cristianbote/hnpwa-vanilla#12]
Is there a global cli tool that is implied in the `README.md`? I can't `npm run serve` or `npm run-prod` because neither is present in `package.json`.
```
➜  hnpwa-vanilla git:(master) ✗ npm run serve
npm ERR! missing script: serve
```

```
➜  hnpwa-vanilla git:(master) ✗ cat package.json | jq .scripts
{
  "build-sw": "node sw-build.js",
  "html-minify": "node html-minify.js",
  "copy-assets": "node copy-assets.js",
  "bundle": "microbundle --output public --target browser --format cjs",
  "build-prod": "rm -rf public; npm run bundle; npm run copy-assets; npm run build-sw; npm run html-minify",
  "deploy": "npm run build-prod; firebase deploy"
}
```

**Comment by cristianbote** [comment]
Hey @steventsao,

Thank you for submitting this issue. Indeed, when going from webpack to microbundle the `serve` script got lost somewhere, sorry for that.

@satyakresna filed an PR here https://github.com/cristianbote/hnpwa-vanilla/pull/11 trying to update the README, but I've totally forgot to reply to him.
Bottom line, update your master, and you'll notice a `serve` script.

Let me know if there's something else you're struggling with. Closing.
Cheers!

**Comment by steventsao** [comment]
Thanks!
