### ISSUE TITLE
Firebase: not found

### ISSUE THREAD

**Issue by mylastore** [cristianbote/hnpwa-vanilla#13]
not sure what this means: sh: 1: firebase: not found

**Comment by cristianbote** [comment]
Hey Oscar(@reachdevelopers),

Have you tried a `npm install` before running it? `firebase` should install after that. Please let me know if this fixed it.

Thanks for submitting!

**Comment by mylastore** [comment]
I did npm install

**Comment by cristianbote** [comment]
Uh, alrighty.

Do you have more info? Was this after a `npm run` command? What's your OS?
Meanwhile, I'll look into it as well.

Again, thanks for reaching out!

**Comment by mylastore** [comment]
I download it again and same thing sh: 1: firebase: notfound
also: Failed at the hnpwa-vanilla@2.1.3 serve script.


Linux Mint 17.3
node: v8.9.0
npm: 5.5.1

**Comment by cristianbote** [comment]
Hey @reachdevelopers you are indeed right. The dependency was pointing to the firebase sdk not the firebase-tools to be able to to serve it locally. A `npm i` should do it now.

Let me know if there are more issues.

Thanks for reaching gout!
