### ISSUE TITLE
Get error 401 (invalid credentials) after run npm run serve

### ISSUE THREAD

**Issue by kresnasatya** [cristianbote/hnpwa-vanilla#15]
Hi @cristianbote, it has been long time I don't check this project. I would like to test in locally by run `npm run serve` but Firebase give response error HTTP Error 401 like below:

```
Error: HTTP Error: 401, Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
```

Is that I'm missing something? I have tried to set up a Firebase project with the name `hnpwa-vanilla` and firebase give the project id name: `hnpwa-vanilla-a2008`. I run command explicitly `firebase serve -p 8080 --project hnpwa-vanilla-a2008` and it still gives response HTTP error 401.

**Comment by kresnasatya** [comment]
Hi @cristianbote, could you help me with this issue?

**Comment by cristianbote** [comment]
Hey, so sorry. For some reason I forgot to press comment on and that tab got discarded 😞. Anyway, for local development I think I need to get rid of firebase, since it's not doing anything special. I'll switch it to `serve` since `microbundle` will take care of the rebuild.

**Comment by cristianbote** [comment]
Fixed

**Comment by kresnasatya** [comment]
Thanks a lot @cristianbote. 🙏🏽
