### ISSUE TITLE
(feature) Dark mode

### ISSUE THREAD

**Issue by cristianbote** [cristianbote/hnpwa-vanilla#18]
It wasn't a thing back then, it is now.

**Comment by gersongams** [comment]
Hi @cristianbote this is the preview of the app with the dark mode. I hope you like it.

![image](https://user-images.githubusercontent.com/12853243/67471875-c6b4e200-f615-11e9-8bee-d13bb2d8bc76.png)

**Comment by cristianbote** [comment]
Awesome job @gersongams 🎉 ! Your changes are live! Congrats and thank you!
